### ISSUE TITLE
Error with compilation

### ISSUE THREAD

**Issue by astrofrog** [radio-astro-tools/casa-python#11]
```
    gcc -pthread -fno-strict-aliasing -g -O2 -g -pipe -Wall
-Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector
--param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC
-DNDEBUG -g -O2 -g -pipe -Wall -
Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector
--param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fPIC
-I/home/schilke/software/casapy-42.2.30986-1-64b/lib64/python2.7/site-packages/numpy/core/include
-I/home/schilke/software/casapy-42.2.30986-1-64b/include/python2.7 -c
astropy/table/_np_utils.c -o
build/temp.linux-x86_64-2.7/astropy/table/_np_utils.o
    astropy/table/_np_utils.c:257:31: fatal error: numpy/arrayobject.h:
No such file or directory
     #include "numpy/arrayobject.h"
                                   ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command
/home/schilke/software/casapy-42.2.30986-1-64b/lib64/casapy/bin/python
-c "import setuptools,
tokenize;__file__='/tmp/pip_build_schilke/astropy/setup.py';exec(compile(getattr(token
ize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__,
'exec'))" install --record /tmp/pip-Z9pwtH-record/install-record.txt
--single-version-externally-managed --compile --user:
    git submodule command failed unexpectedly:
```

So the problem was that the program expected arrayobject.h to be in
include/python2.7/numpy, while it actually was in include/numpy.  Wrong
path. include/python2.7/numpy does not exist

**Comment by iancze** [comment]
First of all, thanks for the great script, I've normally had nothing but success with it. However, upon recently installing it to a new machine I have encountered a possibly related issue (I'm using `CASA Version 4.6.0-REL (r36590)` and the current version of `setup_casapy_pip.py`). The script installs fine, but then when I wish to install packages that require compilation (cython, astropy, hdf5, etc) I get the following error

```
gcc -pthread -fno-strict-aliasing -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -DNDEBUG -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fPIC -I/home/ian/.build/casa/casa-release-4.6.0-el6/include/python2.7 -c /tmp/pip_build_ian/cython/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-2.7/tmp/pip_build_ian/cython/Cython/Plex/Scanners.o

/tmp/pip_build_ian/cython/Cython/Plex/Scanners.c:4:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

```

It seems like installing python-dev is necessary, but I cannot figure out how do this so that CASA knows about it. `casa-pip install python-dev` results in an unknown package. Do you have any pointers on what type of libraries to install or link to in order to enable compilation of these packages? Thanks!

**Comment by astrofrog** [comment]
@iancze - this is a known issue with CASA 4.6.0 and there is no way around it other than using one of the CASA 4.7 pre-releases or downgrading to CASA 4.5.3 (unless they release CASA 4.6.1)

**Comment by astrofrog** [comment]
(the original issue here was with CASA 4.2 which was also missing some header files)

**Comment by iancze** [comment]
Hi Tom, thanks a lot for your help. I tried using the latest pre-release (casa-monthly-4.7.16) and I ran into the same problem with `Python.h`.

However, I tried CASA 4.5.3 and things work as expected. 

I tried searching through https://casa.nrao.edu/hdtickets to see if this had been reported for the 4.7 release, but I couldn't find anything. I'm assuming if this is a known bug for 4.6 then it is also on track to be fixed for 4.7, but if not I can submit a helpdesk ticket.

**Comment by astrofrog** [comment]
@iancze - I think the issue was fixed in 4.7.30 (stable) and was indeed still broken in 4.7.16. Can you try the latest 'stable' version to let me know if that works?

**Comment by iancze** [comment]
Ahh, I didn't realize I had only tried the latest monthly. I just installed `casa-stable-4.7.51` and everything works like a charm :grinning: Thanks for your help, @astrofrog !!

**Comment by astrofrog** [comment]
@iancze - no problem!
