### ISSUE TITLE
setup_casapy_pip broken by casa-release-4.3.0

### ISSUE THREAD

**Issue by david-terrett** [radio-astro-tools/casa-python#12]
With CASA 4,3,0 installed from casa-release-4.3.0-el6.tar.gz setup_casapy_pip fails because:

1) the CASA library directory is now called lib and not lib64
2) lib/casapy is now called lib/casa
3) The script detects the wrong python version because lib/python2.6 exists but the python version is 2.7

**Comment by astrofrog** [comment]
Thanks - I think that we should actually be able to simplify this wrapper a lot anyway with 4.3. @keflavich - did we establish if 4.3 has the 'shortcut' to the Python interpreter?

**Comment by astrofrog** [comment]
Also, if it does, then we should simply drop support for <4.3 because that was mainly a hack.

**Comment by keflavich** [comment]
@astrofrog - I totally missed this issue... I don't know.  I just committed to demoing this next week, though, so I'll work on figuring it out...

**Comment by keflavich** [comment]
@astrofrog: looks like 'no' - I think that was dumped to 4.4.  Sigh.

I get this traceback:
```
$ python setup_casapy_pip.py
Traceback (most recent call last):
  File "setup_casapy_pip.py", line 245, in <module>
    python_version = get_python_version_mac()
  File "setup_casapy_pip.py", line 51, in get_python_version_mac
    casapy_path = get_casapy_path()
  File "setup_casapy_pip.py", line 43, in get_casapy_path
    raise SystemError("Could not locate casapy command")
SystemError: Could not locate casapy command
```

**Comment by astrofrog** [comment]
Huh, but when you launch CASA on Mac it should add it to your path.

**Comment by keflavich** [comment]
Probably in most cases, yes.  Not on my testing setup, though, where I have a headless machine.

**Comment by astrofrog** [comment]
Ah wait, I think that may be a link leftover from a previous install....

**Comment by keflavich** [comment]
In any case, #13 solves this (on a mac)

**Comment by david-terrett** [comment]
I am running CASA on Linux –not Mac.

David

**Comment by astrofrog** [comment]
By the way, if one goes inside the application, you can find ``casa-config`` and now do:

```
/Applications/CASA.app/Contents/MacOS/casa-config --exec python
Python 2.7.6 (default, Jun  9 2014, 20:07:34) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

so that may work - however I remember that @trhunter said that this still wasn't able to install Astropy.

**Comment by astrofrog** [comment]
``casa-config --exec python`` should work on Linux too so we should check if we can use that to simplify the wrapper, and check whether there are still issues installing e.g. astropy.

**Comment by astrofrog** [comment]
Just FYI I'm going to try and work on this

**Comment by keflavich** [comment]
@david-terrett with #14 merged, this may be fixed.

**Comment by trhunter** [comment]
Today, I tried the latest casa-python and was able to use it successfully to "casa-pip install astropy" and then "import astropy" into casa 4.3.1 on both my Macbook (Yosemite) and Ubuntu workstation.

**Comment by keflavich** [comment]
thanks @trhunter!  Marking this fixed.
